name: EnchantmentInfoUI
main: EnchantmentInfoUI\EnchantmentInfoUI
author: PedsHampton
version: 1.0.0
api: [3.0.0, 3.5.1]
commands:
  enchantmentinfo:
    aliases: [enchantinfo, einfo, enchinfo]
    description: Checks Info On A VanillaEnchantment
    permission: enchantmentinfo.use
    default: true
permissions:
  enchantmentinfo.use
  default: true
  description: Allows Player To Check Info On A VanillaEnchantment
